services:
  streamly_db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: streaming
    volumes:
      - postgres_data:/var/lib/postgresql/data

  streamly_minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data

  streamly:
    image: ghcr.io/sahilk1234/streamly:latest
    restart: unless-stopped
    depends_on:
      - streamly_db
      - streamly_minio
    environment:
      DATABASE_URL: postgresql://postgres:postgres@streamly_db:5432/streaming
      NEXTAUTH_SECRET: prod-secret
      NEXTAUTH_URL: https://streamly.sahilkhadtare.com

      MEDIA_STORAGE: local
      LOCAL_MEDIA_DIR: /app/storage

      RUN_DB_SEED: "true"
      RUN_DEMO_DOWNLOAD: "true"

    ports:
      - "3000:3000"
    volumes:
      - ./storage:/app/storage

volumes:
  postgres_data:
  minio_data:
